# Site settings
title: Ang Bagoong Lipunan
email: overlord@archon-digital.com
description: "A fictional republic in South East Asia run by an oppresive regime. The regime came unto power through Executive Order No. 118, dissolving the elected Senate and House of Representatives as well as suspending the writ of habeas corpus and suppression of free speech."
baseurl: "/bagoongsociety/"
url: "http://archon.digital"
username: archondigital
timezone: Asia/Manila
paginate: 10
paginate_path: "articles/:num"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-redirect-from
- jekyll-paginate
#   - jekyll-sitemap

# ads, analytics and disqus
enable_disqus: true
enable_adsense: true
enable_analytics: true
